### ISSUE TITLE
Define users, objects and permissions

### ISSUE THREAD

**Issue by Natim** [mozilla-services/kinto#33]
# Objects

I have identified three kinds of objects:

 - *bucket*: A set of collection
 - *collection*: A set of records with permission and schema
 - *record*: To share some record of a collection.

For bucket, we only need to have a list of owners that have admin rights on the bucket.

For collections we can have permissions on each level of a collection:

 - The *collection existence*: Today as soon as you access it it exists but you may want to clear it all
 - The *collection records*: CRUD Any of them, some of them
 - The *collection permissions*: Read and Update
 - Eventually the *collection schema*: Read and Update

# Permissions

Here is a proposal to handle collection sharing and users permissions

## The collection owner can change permissions and give specific access to some other users

At first we could only let the collection owner manage permissions on her collection and just delegate the following rights:

- *create_record*: add new records to the collection

- *read_all_records*: read any collection's records
- *update_all_records*: update any collection's records
- *delete_all_records*: delete any collection's records

- *read_shared_records*: read records shared with you (your principal is set on the record)
- *update_shared_records*: update and change records shared with you
- *delete_shared_records*: delete records shared with you

IMHO this could be enough for our current use cases.

## The collection owner can also add admin (Also works for the orga model)

A second enhancement could be to go further in this and let you define administrators on the collection, you can then share a collection with someone and let her do:

- *read_permissions*: read the model permissions (who can do what)
- *update_permissions*: change the permissions for the model
- *delete_collection*: delete the collection and all its data

## Everything is flexible and go through permissions

An alternative would be to have a list of these 10 permissions and let the owner define them for any users and then check if the permissions is present for the user.

This will let us have more flexibility.

**Comment by ametaireau** [comment]
Thanks for starting this discussion! I've also wrote something on my side that I'm posting it in a first comment before actually comenting on your proposal. I feel doing so before actually reading your proposal specifically could allow us to open up some thoughts.

From yesterday's discussion, we agreed that a good way to approach this problem was to split the discussions into 3 different ones:

- Define a list of permissions and a list of object on which they can be applied;
- Define how we want to handle principals (what they are and how to we obtain them);
- Define what the API should look like at the HTTP level.

# Define a list of permissions and a list of object on which they can be applied

## List of permissions

Permissions are the basic rights one can have on any object. I believe they are:
- read an existing <object>
- create a new <object>
- delete <object>
- update an existing <object>

I don't think we should have a concept of "sharing" defined in the permissions, and I would focus on the real use case: anybody who can read actually can share.

## List of objects on which we can apply permissions

We can apply these permissions on:
- all user's collections (*authorize the creation of collections to someone else*)
- a specific user's collection (*authorize someone to create new records in my collection*)
- records of a specific user's collection (*authorize someone to read all records of the collection*)
- specific `collection_records` (*authorize someone to modify a specific record of the collection*)
- `colletion_schema` (*authorize someone to update the collection schema*)

In addition to that, I believe we don't need to define an object for the permissions itself: whoever can update a record can change its associated permissions.

For each object, some permissions might not make sense and could be removed (for instance, updating or deleting a collection_schema might not make sense).

I feel the discussion about principals should go in a different issue so I opened #35.

**Comment by ametaireau** [comment]
An now here is a comment on your proposal!

> we only need permissions on Collections

I also think we need permissions at the root level (so it's possible to have someone share all collections of someone else for instance).

About permissions, we might not need to define an object for the permissions itself by statgin that "whoever can update a record can change its associated permissions".

> The collection owner can change permissions and give specific access to some other users

I believe we could have that by just using the "write" permission to the "collection" object.

I believe my proposal is along the lines of your 3rd use case: "Everything is flexible and go through permissions"

**Comment by Natim** [comment]
> whoever can update a record can change its associated permissions.

Yes

> anybody who can read actually can share

It might be true to add someone but what about read/write and removing someone?

**Comment by ametaireau** [comment]
Oh, I get where you're coming from. By sharing, I was only thinking about sharing the same access level.

e.g. if you have the rights to read and write, then you can give anyone else this same right.
